### ISSUE TITLE
MSI Installer for 1.8_201-1-ojdkbuild hangs

### ISSUE THREAD

**Issue by btreut** [ojdkbuild/ojdkbuild#67] opened 2019-02-13 17:05 UTC
I am trying to install the OpenJDK build 1.8_201 with webstart and update notifier on Windows 10 and the installation stalls (since 24 hours). Hitting Cancel does not have any consequences. I cannot find any hint in the event log, but I also do not know exactly, where I should look for any detailed messages.

![grafik](https://user-images.githubusercontent.com/8996291/52729568-b5f99a00-2fb9-11e9-9ddf-dd1bb85efbbf.png)

**Comment by ojdkbuild** [comment] 2019-02-13 17:48
Hi, thanks for report, to recover the installation you can do the following:

 - reboot the machine (assuming this is possible for that machine)
 - uninstall all previous jdk versions if any
 - do a full install of this MSI
 - do an uninstall

I've never got the described problem with released installers, but had it while experimenting and the steps above worked for me.

About the problem itself, I am interested to understand, why it happens. It would be great if you can reproduce this with logging enabled, running `msiexec` the following way:

    msiexec /q /i jdk.msi ADDLOCAL=<set of features> /Lv* <path to log file>

Where `set of features` can be taken from [wiki](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures).

To install all features: `ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_env_vendor_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env,update_notifier`.

Also, were there any previous versions (x86_64 or x86) already installed before hitting this on 8u201 installation?

**Comment by btreut** [comment] 2019-02-14 09:30
> Also, were there any previous versions (x86_64 or x86) already installed before hitting this on 8u201 installation?

last in, first out: yes, there are several Java versions currently installed, I'll remove them all:

1. Oracle JDK 1.8_202 in 64 bit and 32 bit version 
2. OpenJDK 1.8.0.181-1 in 64bit version

**Comment by btreut** [comment] 2019-02-14 12:00
after reboot there was no trace of the directory %ProgramFiles%\ojdkbuild\java-1.8.0-openjdk-1.8.0.201-1

Now I tried to execute the installer via:
msiexec /q /i java-1.8.0-openjdk-1.8.0.201-1.b09.ojdkbuild.windows.x86_64.msi ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_env_vendor_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env,update_notifier /Lv* ojdk-1.8.0.201.log
in the directory, where the installer was stored. But there is not any apparent sign that the installer runs. The command prompt returns and no GUI window opens. I also do not find any task in the task manager.
But, reading through msiexec /? I realize that this may be the expected result of the /q option. The log file is attached, but there is no newly created directory in %ProgramFiles%\ojdkbuild
[ojdk-1.8.0.201-0.log](https://github.com/ojdkbuild/ojdkbuild/files/2864818/ojdk-1.8.0.201-0.log)

Now, I left out the /q option (as trying to read the info in thelog file it appears to me that without GUI there won't be any UAC elevation query asked, but it will silently exit). This time it looks much better, the
installer GUI pops up, I checked that everything looks ok, and after some time the UAC question pops up,
I allow the installer to modify %ProgramFiles%, and the installer proceeds until 
![grafik](https://user-images.githubusercontent.com/8996291/52785204-b6e10900-3057-11e9-8ac1-40d9b957ea2f.png)
it appears to be a slightly longer progress bar, but I doubt that  it can be trusted.
Now there is also a newly created %ProgramFiles%\java-1.8.0-openjdk-1.8.0.201-1 directory with some contents. The logfile says the following:
[ojdk-1.8.0.201-1.log](https://github.com/ojdkbuild/ojdkbuild/files/2864850/ojdk-1.8.0.201-1.log)

**Comment by ojdkbuild** [comment] 2019-02-14 12:27
> ojdk-1.8.0.201-0.log

Ah, yes, `msiexec` with `/quiet` switch needs to be run from an elevated terminal.

> ojdk-1.8.0.201-1.log

Thanks! This is helpful, installation hangs on registering Task Scheduler task. Can you check whether task `ojdkbuild_jdk_update_checker` already exists in the Task Scheduler before the installation? I can reproduce this locally if I create a task with such name before installing 8u201.

This is unlikely situation - there is an `ojdkbuild_` prefix to a task name, so name clash is unlikely, and old task (from previous version) is deleted on update or uninstall. Still this is a bug and situation when tasks already exists must be handled in installer.

**Comment by btreut** [comment] 2019-02-14 13:07
yes, that task is existing. I guess it is there because I insstalled 8u181 some time ago and did not uninstall before installing 8u201.

> old task (from previous version) is deleted on update

apparently this is not working correctly

**Comment by ojdkbuild** [comment] 2019-02-14 13:22
Just checked it, 8u181 correctly drops its Task Scheduler tasks on both uninstall and update to 8u201.

Possibly in your case its uninstall wasn't finished for some reason and tasks weren't unregistered from Task Scheduler. In any way, this case must be handled on install.

**Comment by btreut** [comment] 2019-02-14 13:52
OK. I'll uninstall all currently installed java versions and I'll try again.

**Comment by btreut** [comment] 2019-02-14 14:31
The situation is a little bit strange: It looks like 8u181 is installed (i.e. its directory exists and its bin directory is present in the path), the Update Notifier is registered in the Task Scheduler etc., but when I try to uninstall it via msiexec /uninstall java...181..msi it tells me that this action is only possible for installed products.

**Comment by ojdkbuild** [comment] 2019-02-14 14:39
This may be related to the user account that was used to install it. There was recently [an issue](https://bugzilla.redhat.com/show_bug.cgi?id=1661198) that is not directly related to this problem, but may be somewhat similar.

Or just some "incomplete uninstall" happened (e.g. reboot on uninstall). I suggest to try to install and then uninstall 8u181.

Also, to fix the 8u201 hanging problem it should be enough to delete `ojdkbuild_*` tasks from Task Scheduler manually.

**Comment by btreut** [comment] 2019-02-15 08:44
thanks. It may be related to the mentioned issue since this is also a managed PC (although I have/can elevate my account to administrative privilegies). On the other hand after reinstalling 8u181 it appears in the list of installed programs. I'll follow up on Tuesday ...

**Comment by ojdkbuild** [comment] 2019-03-01 12:46
This is [fixed](https://github.com/ojdkbuild/contrib_update-notifier/commit/4f3e85f9e5852c12f26f506d298fce6b8afda430) deleting the tasks with these names first before attempting to register them. Going to be included with 8u211 (or 8u212) installer in April.

**Comment by btreut** [comment] 2019-03-06 13:11
sorry for the delay. After re-installing 8u181, the update to 8u201 went flawless without stalling. Opening a cmd window and executing java -version still shows 8u181. The PATH environment variable has both, first 8u181 and second 8u201 in it, which explains why it finds 8u181 first. I removed 8u181 manually from the path.

**Comment by ojdkbuild** [comment] 2019-03-06 16:46
Thanks for the details, this definitively looks like two installations under different users and incomplete uninstallation for at least one of them. This shouldn't happen with 8u211 (which is switched to "perMachine" install).

**Comment by ojdkbuild** [comment] 2019-04-24 12:48
The fix is included with [8u212 release](https://github.com/ojdkbuild/ojdkbuild/releases/tag/1.8.0.212-1), closing the issue, please re-open if needed.

Note, that update from 8u201 to 8u212 will NOT work, 8u201 needs to be uninstalled first.

**Closed by ojdkbuild** 2019-04-24 12:48 UTC
