### ISSUE TITLE
rescources/scripts/build-all.bat fails on deleting build directory

### ISSUE THREAD

**Issue by orithena** [ojdkbuild/ojdkbuild#55] opened 2018-11-27 09:51 UTC
I'm trying to build openjdk using the `resources/scripts/build-all.bat`.

Unfortunately, after successfully building the installer (line 48), the script exits after trying to delete the build directory:
```
build\java-1.8.0-openjdk\jdk\gensrc\java\nio\_the.. - Das System kann die angegebene Datei nicht finden.
build\java-1.8.0-openjdk-boot\jdk\gensrc\java\nio\_the.. - Das System kann die angegebene Datei nicht finden.
```
The german error message basically translates to "File not found" ... but those two malformed files (at least to windows tools) remain.

Running `rmdir /s /q build` produces the same problem, so I assume that the batch process exits on line 52. Removing the build directory using `rm -rf` on the git shell deletes those files.

Now I'm wondering ... is this just a problem with windows or is the existence of these files a symptom of an earlier problem? It almost looks like these filenames have been generated using empty variables that should not have been empty.

**Comment by ojdkbuild** [comment] 2018-11-27 19:42
Thanks for the report! Let me re-check this with a full clean build. It well may be possible, that jdk during the builds writes some files through cygwin, with names, that are not supported by `rmdir`.

**Comment by orithena** [comment] 2018-11-28 12:51
In the meantime, I checked out the latest commit (b5540b9, "jdk8 build cleanup") and re-built. I just added an `exit /b 0` after the first `nmake installer` and before the build directory is deleted, so I did not run into the problem directly.

The `_the..` files still are there and I presume that they still cannot be deleted by windows' rmdir (output generated using git bash for windows):
```
user@machine MINGW64 ~/ojdkbuild/build (master)
$ find -ipath "*nio*/_the*"
./openjdk/bootcycle-build/jdk/demo/nio/zipfs/_the.zipfs.jar_manifest
./openjdk/bootcycle-build/jdk/democlasses/nio/zipfs/_the.BUILD_DEMO_zipfs_batch
./openjdk/bootcycle-build/jdk/democlasses/nio/zipfs/_the.zipfs.jar_contents
./openjdk/bootcycle-build/jdk/gensrc/java/nio/_the..
./openjdk/bootcycle-build/jdk/gensrc/java/nio/_the.buffer.dir
./openjdk/bootcycle-build/jdk/gensrc/java/nio/_the.channels
./openjdk/bootcycle-build/jdk/gensrc/java/nio/_the.charset
./openjdk/bootcycle-build/jdk/gensrc/java/nio/_the.exceptions.dir
./openjdk/jdk/demo/nio/zipfs/_the.zipfs.jar_manifest
./openjdk/jdk/democlasses/nio/zipfs/_the.BUILD_DEMO_zipfs_batch
./openjdk/jdk/democlasses/nio/zipfs/_the.zipfs.jar_contents
./openjdk/jdk/gensrc/java/nio/_the..
./openjdk/jdk/gensrc/java/nio/_the.buffer.dir
./openjdk/jdk/gensrc/java/nio/_the.channels
./openjdk/jdk/gensrc/java/nio/_the.charset
./openjdk/jdk/gensrc/java/nio/_the.exceptions.dir
```

Judging from the other files, I presume that these filenames are being generated using a template like `_the.${SOMEVARIABLE}` with SOMEVARIABLE containing a single dot (for "current directory", maybe?) at some point. Sadly, the build process is still too opaque to me to identify the source.

**Comment by ojdkbuild** [comment] 2018-11-28 13:00
I cannot easily reproduce this, the `build-all.bat ` works for me locally for `jdk8-x86_64` (it fails later for `x86` for unrelated reasons). I am using `c:\ojdkbuild` path (in case this is related to overly-long paths problem).

The generation logic for NIO is [here](https://github.com/ojdkbuild/lookaside_java-1.8.0-openjdk/blob/master/jdk/make/gensrc/GensrcBuffer.gmk), it is not straightforward, but this Makefile hasn't changed for a very long time.

**Comment by orithena** [comment] 2018-11-28 16:22
@ojdkbuild Well, I tried to build it in C:\ojdkbuild, but that build failed even more spectacularly. We suspect the company-wide virus scanner to heuristically restrict some executable behaviours and being more lenient inside the user home...

**Comment by ojdkbuild** [comment] 2018-11-28 23:19
I suggest to not use `build-all` script and to call cmake and nmake directly. If every single build is okay it may be easier to rename the build dir or use different build dirs (or something like that) to avoid problems with "cleanup immediately after the build".

I will look more at the NIO generation script, but with no recent changes it is unlikely it is doing something wrong.

**Comment by ojdkbuild** [comment] 2019-02-05 13:38
This appeared to be [JDK-8007897](https://bugs.openjdk.java.net/browse/JDK-8007897). It hasn't cause problems before, because `rd /s /q build` or `rd /s /q "build/openjdk/jdk/gensrc/java/nio"` works fine on win2012. But the file `_the..` still causes problems in windows explorer and probably with some other tools.

Fix looks non-intrusive, I [added it to jdk8 tree](https://github.com/ojdkbuild/lookaside_java-1.8.0-openjdk/commit/77fc8ca355c34ce97ea1ba0d7c6cb54961bea110).

Closing the issue.

**Closed by ojdkbuild** 2019-02-05 13:38 UTC
