### ISSUE TITLE
Support building with MSYS2 as external environment

### ISSUE THREAD

**Issue by quanah** [ojdkbuild/ojdkbuild#77] opened 2019-04-02 00:21 UTC
It's trivially possible to build (at least OpenJDK12) from your repo with MSYS2 as the outer environment with the following changes:

```
$ git diff .
diff --git a/make/autoconf/build-aux/autoconf-config.sub b/make/autoconf/build-aux/autoconf-config.sub
index 1aab2b303..8c1d24db7 100644
--- a/make/autoconf/build-aux/autoconf-config.sub
+++ b/make/autoconf/build-aux/autoconf-config.sub
@@ -1274,7 +1274,7 @@ case $os in
              | -bosx* | -nextstep* | -cxux* | -aout* | -elf* | -oabi* \
              | -ptx* | -coff* | -ecoff* | -winnt* | -domain* | -vsta* \
              | -udi* | -eabi* | -lites* | -ieee* | -go32* | -aux* \
-             | -chorusos* | -chorusrdb* \
+             | -chorusos* | -chorusrdb* | -msys* \
              | -cygwin* | -pe* | -psos* | -moss* | -proelf* | -rtems* \
              | -mingw32* | -linux-gnu* | -linux-newlib* | -linux-uclibc* \
              | -uxpv* | -beos* | -mpeix* | -udk* \
diff --git a/make/autoconf/platform.m4 b/make/autoconf/platform.m4
index 39134d121..ded491c64 100644
--- a/make/autoconf/platform.m4
+++ b/make/autoconf/platform.m4
@@ -192,6 +192,10 @@ AC_DEFUN([PLATFORM_EXTRACT_VARS_FROM_OS],
       VAR_OS=windows
       VAR_OS_ENV=windows.msys
       ;;
+    *msys*)
+      VAR_OS=windows
+      VAR_OS_ENV=windows.cygwin
+      ;;
     *aix*)
       VAR_OS=aix
       VAR_OS_TYPE=unix
```

**Comment by ojdkbuild** [comment] 2019-04-02 13:20
No, sorry, I really don't like this idea. From the first hand experience all these "*nix emulation layers" are super-brittle and, given the complexity of OpenJDK/OpenJFX build scripts, can break in an innumerable ways. In this project, fixed versions of Cygwin are used for each LTS jdk and going to continue being used without changes until the EOL of this jdk version.

For some future version, mainline OpenJDK build may switch to [WSL](https://docs.microsoft.com/en-us/windows/wsl/about) ([maillist link](http://mail.openjdk.java.net/pipermail/build-dev/2019-January/024653.html)), that should solve most of the problems (*nix emulation inside the windows kernel is no longer an "emulation" :) ), but for the existing LTS versions it is better to keep a stable environment (old Cygwin versions).

It is of course possible to add MSYS support and continue building with Cygwin, but I'd rather not maintain the patches for scenarios, not actually used for preparing final binaries.

**Comment by quanah** [comment] 2019-04-02 13:43
I think you failed to understand this issue.  I'm not asking you to stop using Cygwin.

If I ssh into my MSYS2 environment and check out and execute the build process (run.bat), it will fail eventually because it doesn't recognized the *outer* layer (MSYS2) as a valid type thus the first patch.

Then it will fail later because the version of GNU make that is in the inner cygwin environment was compiled for cygwin and cygwin != msys.  The above two patches make it possible to build things as they *currently* are (i.e., with the embedded cygwin used for the build process).

**Comment by ojdkbuild** [comment] 2019-04-02 16:44
Sorry, yes I missed the "outer environment" part. Re-opening the issue, as this looks like a valid use case.

**Comment by ojdkbuild** [comment] 2019-05-07 22:39
M, for some reason I cannot reproduce this, running the following script:

    @echo off
    cd c:\ojdkbuild\
    call resources\scripts\set-compile-env-vs15-x86_64.bat
    rd /s /q build
    mkdir build
    cd build
    cmake ../src/java-12-openjdk
    nmake openjdk

From this env (comes with win-git):

    $ uname -a
    MINGW64_NT-6.3 WIN-VFSS8N6L60A 2.7.0(0.307/5/3) 2017-02-17 14:20 x86_64 Msys
    $ cmd.exe
    > test.bat

And it works fine for me. Should I use some specific version of MSYS2 to reproduce this?

**Comment by quanah** [comment] 2019-05-07 22:52
Your uname -a doesn't match mine at all:

```
$ uname -a
MSYS_NT-10.0 DESKTOP-EV1G963 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys
```

Most particularly, your install is reporting MINGW64_NT rather than MSYS_NT, and your build is much much older.  Did you install msys rather than msys2?

I installed msys2 from https://www.msys2.org/

then:

```Start a normal MSYS2 terminal window:

    Update all packages
        pacman -Syuq
    Close the terminal window (You have to do this twice because the first time it'll fail after updating the subsystem)
        pacman -Syuq
    Use pacman to install necessary packages:
        pacman --needed -Sy patch zip bzip2 perl unzip autoconf automake libtool bison tar flex texinfo git \
        openssh cygrunsrv mingw-w64-x86_64-editrights base-devel msys2-devel mingw-w64-{x86_64,i686}-toolchain \
        mingw32/mingw-w64-i686-nsis mingw64/mingw-w64-x86_64-nsis make diffutils dos2unix
    Finish install
        pacman -Rsc gcc
```

It will require adding a few more packages via pacman, the above was for my company's product. ;)

**Comment by ojdkbuild** [comment] 2019-05-20 19:32
Sorry for delay, I've done some more experiments, learned about msys/msysgit/msys2 difference and asked for the advice on [mailing list](https://mail.openjdk.java.net/pipermail/build-dev/2019-May/025558.html).

I don't want to keep this patch locally, but will happily use it, if it is accepted to upstream openjdk.

If you'd like to [contribute it there](https://openjdk.java.net/contribute/), I can suggest to discuss the changes in the same maillist thread linked above. The note about "corresponding wrapper" there means that change should go to [config.sub](https://hg.openjdk.java.net/jdk/jdk/file/46ae54c3026d/make/autoconf/build-aux/config.sub) instead of `autoconf-config.sub`. I can assist with creating Jira issue if that is needed, but generally don't want to own this change (because I don't use msys2).

Minor note: please refrain from linking this project on the maillist unless necessary - there is nothing secret about it, but it is generally frowned upon promoting "vendor builds" on upstream lists.

I will close this issue here, and will wait for the upstream patch.

**Closed by ojdkbuild** 2019-05-20 19:32 UTC
