### ISSUE TITLE
Building x64 Windows problem

### ISSUE THREAD

**Issue by eix128** [ojdkbuild/ojdkbuild#111] opened 2020-03-20 06:32 UTC
D:\repo\ojdkbuild\build>nmake installer

Microsoft (R) Program Maintenance Utility Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

[  4%] Built target freetype_static
[  4%] Built target freetype
[  4%] Built target ojdkbuild_freetype
[ 10%] Built target libjpeg-turbo
[ 10%] Built target external_libjpeg-turbo
[ 11%] Built target gif
[ 11%] Built target external_giflib
[ 13%] Built target z
[ 14%] Built target z_altcr
[ 14%] Built target external_zlib
[ 16%] Built target png
[ 16%] Built target external_libpng
[ 16%] Copying icons ...

                                D:\repo\ojdkbuild\resources\installer\instres\icon.ico

                                D:\repo\ojdkbuild\resources\installer\instres\icon.png

[ 16%] Built target icons
[ 16%] Copying timezone data ...

[ 16%] Built target tzdata
[ 16%] Preparing build directory ...
[ 16%] Built target builddir
[ 16%] Building OpenJDK ...
      1 [main] bash 7540 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
D:/repo/ojdkbuild/src/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 24: $'\r': command not found                                                                                                                     D:/repo/ojdkbuild/src/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 27: $'\r': command not found                                                                                                                     : No such file or directory1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 30: cd: D:/repo/ojdkbuild/src/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk                                                              D:/repo/ojdkbuild/src/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 31: $'\r': command not found                                                                                                                     /common/autoconf/configure: No such file or directory                                                                                                                                                                                        NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.

**Comment by ojdkbuild** [comment] 2020-03-20 08:41
Hi, this looks like a problem with git auto-converting line endings on checkout, see [details in this issue](https://github.com/ojdkbuild/ojdkbuild/issues/12#issuecomment-282571747). Please check that `core.autocrlf` is set to `false` or `input`.

**Comment by eix128** [comment] 2020-03-20 09:16
Seems like PATH is broken.

call "resources/scripts/set-compile-env-vs10-x86_64.bat"     

This command deletes old PATH variables.
Git works on cmd by default but when i call

call "resources/scripts/set-compile-env-vs10-x86_64.bat"     

git cmd not found

i fixed it by 
call "resources/scripts/set-compile-env-vs10-x86_64.bat"     

set PATH=%PATH%;"C:\Program Files\Git\bin" 


Now git works but this time i got another problem:

checking msys release... 3.0.7-338.x86_64
checking msys root directory as unix-style path... Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.

/C/Program Files/Git>
checking what kind of 'find' is first on the PATH... unix style
checking for top-level directory... /d/repo/ojdkbuild/lookaside/java-1.8.0-openjdk
configure: Rewriting CURDIR to "/D/repo/ojdkbuild/build/openjdk"
'epo' is not recognized as an internal or external command,
operable program or batch file.
configure: Rewriting TOPDIR to ""
checking for presence of closed sources... no
checking if closed source is suppressed (openjdk-only)... no
checking which variant of the JDK to build... normal
checking which interpreter of the JVM to build... template
checking which variants of the JVM to build... server
checking which debug level to use... release
checking for sysroot...
checking for toolchain path...
checking for extra path...
checking where to store configuration... in current directory
checking what configuration name to use... /D/repo/ojdkbuild/build/openjdk
checking for apt-get... no
checking for yum... no
checking for port... no
checking for pkgutil... no
checking for pkgadd... no
checking for gmake... no
checking for make... /d/repo/ojdkbuild/tools/make/make
configure: Testing potential make at /d/repo/ojdkbuild/tools/make/make, found using make in PATH
      1 [main] make 6856 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
      1 [main] make 13780 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
configure: Found GNU make version GNU Make 3.81 at /d/repo/ojdkbuild/tools/make/make, but it is not for msys (it says: This program built for i686-pc-cygwin). Ignoring.
configure: error: Cannot find GNU make 3.81 or newer! Please put it in the path, or add e.g. MAKE=/opt/gmake3.81/make as argument to configure.
configure exiting with result code 1
NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.

**Comment by ojdkbuild** [comment] 2020-03-20 09:48
> This command deletes old PATH variables.

This is intentional, the problem with `make` is caused by the `PATH` elements order. It is expected that sources (all required submodules) are checked out first and `set-compile-env-*` is used after that.

**Comment by eix128** [comment] 2020-03-20 13:01
So , you should add git to tools

**Comment by eix128** [comment] 2020-03-20 13:02
I am trying more how to solve the issue.Hope to fix it then i will tell you the problem

**Comment by eix128** [comment] 2020-03-20 14:35
configure: Rewriting POTENTIAL_FREETYPE_LIB_PATH to "/cygdrive/d/repo/openjdk/ojdkbuild/build/bin/"
checking for freetype includes... /cygdrive/d/repo/openjdk/ojdkbuild/lookaside/freetype/include/
checking for freetype libraries... /cygdrive/d/repo/openjdk/ojdkbuild/build/bin/
checking if we can compile and link with freetype... yes
checking if we should bundle freetype... yes
checking for which libjpeg to use... ojdkbuild
checking for which giflib to use... ojdkbuild
checking for which libpng to use... ojdkbuild
checking for which zlib to use... ojdkbuild
checking for cos in -lm... yes
checking for dlopen in -ldl... no
configure: Found msvcr100.dll at D:/repo/openjdk/ojdkbuild/src/java-1.8.0-openjdk/../../tools/toolchain/msvcr100/amd64/msvcr100.dll using --with-msvcr-dll
checking found msvcr100.dll architecture... ok
configure: Rewriting MSVC_DLL to "/cygdrive/d/repo/openjdk/ojdkbuild/tools/toolchain/msvcr100/amd64/msvcr100.dll"
checking for msvcr100.dll... /cygdrive/d/repo/openjdk/ojdkbuild/tools/toolchain/msvcr100/amd64/msvcr100.dll
checking if elliptic curve crypto implementation is present... yes
checking for memory size... 130979 MB
checking for appropriate number of jobs to run in parallel... 1
checking whether to use sjavac... no
checking is ccache enabled... no
configure: error: Bad file permissions on src files. This is usually caused by cloning the repositories with a non cygwin hg in a directory not created in cygwin.
configure exiting with result code 1
NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'D:\repo\openjdk\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\openjdk\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\repo\openjdk\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.

**Comment by ojdkbuild** [comment] 2020-03-20 14:55
[This snippet](https://github.com/ojdkbuild/ojdkbuild/issues/12#issuecomment-359251830) should help with " Bad file permissions" problem.

**Comment by eix128** [comment] 2020-03-23 12:33
Well I have migrated to Windows Administrator Account.
Now new problem

[ 96%] Building OpenJDK ...
      1 [main] bash 17236 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com
Running make as '/cygdrive/d/test/ojdkbuild/tools/make/make -s VERBOSE=-s LOG_LEVEL=info -R -I /cygdrive/d/test/ojdkbuild/lookaside/java-1.8.0-openjdk/make/common  SPEC=/cygdrive/d/test/ojdkbuild/build/openjdk/spec.gmk -j1'
Building OpenJDK for target 'images' in configuration '/cygdrive/d/test/ojdkbuild/build/openjdk'

## Starting langtools
Generating stubs from JDK sources.
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/javac/api/JavacTool
        at genstubs.GenStubs.run(GenStubs.java:129)
        at genstubs.GenStubs.run(GenStubs.java:119)
        at genstubs.GenStubs.main(GenStubs.java:95)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 3 more
make[1]: *** No rule to make target `all', needed by `default'.  Stop.
make: *** [langtools-only] Error 2
NMAKE : fatal error U1077: 'C:/WINDOWS/System32\cmd.EXE' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\test\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\test\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'D:\test\ojdkbuild\tools\toolchain\vs2010e\VC\Bin\nmake.exe' : return code '0x2'
Stop.

D:\test\ojdkbuild\build>



I tried
set CLASSPATH=C:\Program Files\Java\jdk1.8.0_241\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_241\lib\tools.jar
then

D:\test\ojdkbuild\build>nmake installer


But the same error occurs again!
Why it is so evil hard to compile OpenJDK 8 on Windows....


I am using x64 Native Tools Command Prompt for all

**Comment by eix128** [comment] 2020-03-25 09:47
I fixed the issue by 

I have activated Administrator account by:
net user administrator /active:yes
net user administrator *

then i deleted all ojdkbuild.
Then remake all step as "Administrator" account.
It fixed the problem.

But i think for all platforms.
It will be better to make docker build.
So everyone can compile without any problem.

**Comment by ojdkbuild** [comment] 2020-05-03 19:59
Closing the issue, please re-open if problem persists.

**Closed by ojdkbuild** 2020-05-03 19:59 UTC
