### ISSUE TITLE
Wrong locale used

### ISSUE THREAD

**Issue by ledahulevogyre** [ojdkbuild/ojdkbuild#105] opened 2019-10-18 14:19 UTC
System.out.println(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG, new Locale("nl")).format(new GregorianCalendar(2019, 9, 15).getTime())); 

The preceding code gives the following on my computer :
October 15, 2019

I expect : 
15 oktober 2019

Using java-1.8.0-openjdk-1.8.0.222-2.b10.ojdkbuild.windows.x86.msi

**Comment by ojdkbuild** [comment] 2019-10-18 19:08
Hi, I am unable to reproduce this, had the following output on Win10:

    > java -version
    openjdk version "1.8.0_222-2-ojdkbuild"
    OpenJDK Runtime Environment (build 1.8.0_222-2-ojdkbuild-b10)
    OpenJDK Server VM (build 25.222-b10, mixed mode)

    > jrunscript -e "Packages.java.lang.System.out.println(Packages.java.text.DateFormat.getDateInstance(Packages.java.text.DateFormat.LONG, new Packages.java.util.Locale(\"nl\")).format(new Packages.java.util.GregorianCalendar(2019, 9, 15).getTime()));"
    15 oktober 2019

Any specifics about the environment where you see this problem?

**Comment by ledahulevogyre** [comment] 2019-10-21 10:20
Thank you for your response.
Your testcase gives me the correct result too. So I need to analyze it further, and I'll get back to you as soon as I have a reduced test case that is meaningful.

**Comment by ledahulevogyre** [comment] 2019-10-22 06:16
Should I post an issue to IcedTea Web ?

**Comment by ojdkbuild** [comment] 2019-10-22 09:31
I can reproduce this, looks like the genuine issue with ITW. It may be a good idea to bring this to `AdoptOpenJDK/IcedTea-Web`. I'll do some more experiments, but that is unlikely that the ojdkbuild packaging of ITW may cause this problem.

**Comment by hendrikebbers** [comment] 2019-10-22 10:13
@ojdkbuild can you reproduce the issue? We just tried on a linux system and the output was correct

**Comment by ojdkbuild** [comment] 2019-10-22 10:27
@hendrikebbers , yes, I can see locally that `DateFormat.getDateInstance(...)` returns instances with different formatting patterns when run on ITW and when run directly. I currently don't understand why that happens and going to debug some more.

**Comment by ojdkbuild** [comment] 2019-10-22 10:54
What I see so far, the difference appears [here](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/dd10fb830ea9/src/share/classes/sun/util/locale/provider/LocaleResources.java#l479), `getDateFormatData` returns different values. When `ResourceBundle` for `nl` locale is loaded from ITW [here](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/dd10fb830ea9/src/share/classes/java/util/ResourceBundle.java#l1339) - `NONEXISTENT_BUNDLE` is returned. It is currently not clear why that happens.

**Comment by ojdkbuild** [comment] 2019-12-24 14:04
This appeared to be not a packaging problem, but the actual problem that was fixed in newer ITW - https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3720 . Applied [the fix](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/a96575c422cba10277936aba353cfaae983e3f84), this is going to be included into January release.

**Comment by ojdkbuild** [comment] 2020-01-18 19:19
8u242 release ([x86_64](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.242-1.b08), [x86](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.242-1.b08-x86)) has been published, closing the issue.

**Closed by ojdkbuild** 2020-01-18 19:19 UTC
