### ISSUE TITLE
Q: msi command line options

### ISSUE THREAD

**Issue by 1of16** [ojdkbuild/ojdkbuild#49] opened 2018-10-26 17:33 UTC
Hi,
hope it is not a stupid question: but how can I install your msi packages without user interaction and installing the webstart option?
as far as I know there are command line parameters to e.g. install optional features.
maybe a wiki-entry would be a good idea :)

**Comment by ojdkbuild** [comment] 2018-10-26 19:10
Hi, `msiexec` has a number of [options](https://docs.microsoft.com/en-us/windows/desktop/Msi/command-line-options), components to install can be listed with commas in `ADDLOCAL` part, example installing all components (listed in the same order as in installer):

    msiexec /q /i jdk.msi ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env,update_notifier INSTALLDIR=c:\tmp\jdk

And to uninstall:

    msiexec /q /x jdk.msi

These commands require `Administrator` privileges (some components may also work from normal user).

For troubleshooting this [article](https://www.advancedinstaller.com/user-guide/qa-log.html) may be useful.

On wiki: yes, I think component names (that became numerous with 8u191) should be documented in wiki, leaving this issue open for that.

**Comment by 1of16** [comment] 2018-10-29 06:12
@ojdkbuild thank you, I couldn't find the ADDLOCAL parameters :)
works like expected

**Comment by ojdkbuild** [comment] 2018-11-14 14:20
Added features list to [wiki](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures), closing the issue.

**Comment by 1ojdkuser** [comment] 2019-07-30 13:03
Hi, ask for help. In the current version the following command line option does not work anymore (under Windows 10):
`msiexec /i "java-1.8.0-openjdk-1.8.0.222-1.b10.ojdkbuild.windows.x86_64.msi" ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env INSTALLDIR="C:\tmp\Java" /qn ...`

**Comment by ojdkbuild** [comment] 2019-07-30 18:04
This may be caused by the addition of JRE features in 8u222 (they probably should have been announced in more details).

With 8u222 [updated list of installer features](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures#openjdk-8-installation-features) two more entries need to be added to the `ADDLOCAL` list for the full install: `jdk_devel` and `jdk_registry_standard_devel`.

Names of the previous features stay the same, but `jdk` feature now only contains JRE part, and the actual JDK part is moved to `jdk_devel` feature.

**Comment by ojdkbuild** [comment] 2019-08-05 09:42
Closing this, please reopen if problem remains

**Closed by ojdkbuild** 2019-08-05 09:42 UTC
