### ISSUE TITLE
Download speed is extremely slow.

### ISSUE THREAD

**Issue by rkimsb2** [ojdkbuild/ojdkbuild#78] opened 2019-04-24 07:48 UTC
IMHO there's something wrong on AWS.

**Comment by ojdkbuild** [comment] 2019-04-24 14:20
This can be caused by different AWS regions or something like that. It works for me with a normal speed now. Leaving the issue open for some time, if there will be more reports, it may worth contacting github about that.

**Comment by ojdkbuild** [comment] 2019-04-30 09:55
Closing the issue, assuming it was a temporary AWS glitch.

**Closed by ojdkbuild** 2019-04-30 09:55 UTC

**Comment by rkimsb2** [comment] 2019-04-30 09:59
I have one more question. Is the Cloudfront enabled?

**Comment by ojdkbuild** [comment] 2019-04-30 10:05
Sorry, I don't know what Cloudfront is. I am just uploading the releases to GitHub and everything else about them (AWS/CDN config) is done on GitHub side.
