### ISSUE TITLE
Add MSI installer build (or make it an option) to run.bat

### ISSUE THREAD

**Issue by quanah** [ojdkbuild/ojdkbuild#75] opened 2019-04-01 23:34 UTC
When the ojdkbuild repository is checked out, the instructions are to execute run.bat

Which builds openjdk just fine, but it only creates the zip files.  It would nice to be able to (optionally) be able to create an MSI installer via run.bat.

Currently, adding "nmake installer" does not work, because it fails due to the path being incorrect in the generated WXS file (Source="missioncontrol\...").  I.e., it is missing either "./missioncontrol" or a build variable in front of missioncontrol so that the various pom.xml files it wants can be found.

**Comment by ojdkbuild** [comment] 2019-04-02 13:01
Yes, the instructions about the builds are outdated, going to update them with the April release. See also #74  .

There are two problems here:

1. `run.bat` was intended to be a "simplest build possible", before the jdk11 it was a jdk8 ZIP (without OpenJFX, installer etc); after introduction of jdk11 it is not clear what a "default" build should do (8, 11, installers etc)

2. generally all build scenarios are really stable at the point of tagged releases; they usually work on tip too, but some of them may remain broken (toolchain change, introduction of new jdk version with some common changes etc) for some time; info about "prefer tagged released" should be added to instructions

Going to update this issue on docs changes.

**Comment by robert-scheck** [comment] 2019-04-20 14:13
Same issue here regarding missing `*.msi` aside of that `run.bat` even does not lead to a `*.zip` file, just to a filled target directory.

**Comment by ojdkbuild** [comment] 2019-04-24 14:22
With April releases out of the door, going to update (rewrite) build docs in a day or two.

**Comment by ojdkbuild** [comment] 2019-04-30 09:55
Added the [HowToBuild](https://github.com/ojdkbuild/ojdkbuild/wiki/HowToBuild) wiki page.

Closing the issue, please feel free to re-open (or file a new one) with the follow-up questions on build process.

**Closed by ojdkbuild** 2019-04-30 09:55 UTC
