### ISSUE TITLE
openjdk-1.8.0.222-2.b10 for windows64 contains malware

### ISSUE THREAD

**Issue by roman-vi** [ojdkbuild/ojdkbuild#91] opened 2019-08-07 07:11 UTC
Hello, 
java-1.8.0-openjdk-1.8.0.222-2.b10.ojdkbuild.windows.x86_64.msi is containing malware as Trend Micro OfficeScan reported.

**Comment by ojdkbuild** [comment] 2019-08-07 12:26
Hi, this may be a false positive, AFAICS [no engines detected malware in that binary on virustotal](https://www.virustotal.com/gui/file/cb4a5f358552b3ee946312df191dac566b24c4b72ef1d0ba757248f7a6ca3cc5/detection).

**Comment by ojdkbuild** [comment] 2019-08-28 10:53
I cannot reproduce this using Trend Micro Maximum Security (I assume it uses the same detection engine as OfficeScan) Version: 15.0.1231, I am getting no threats found for ojdkbuild MSIs and ZIPs. Would appreciate some pointers how to reproduce this with trial versions of Trend Micro.

**Comment by Archimedes5000** [comment] 2019-09-10 08:17
We had the same problem and made a report to Trend Micro. Problem should be fixed now.

**Comment by ojdkbuild** [comment] 2019-09-10 10:58
@Archimedes5000 , thanks for doing that! This is great to know.

**Comment by ojdkbuild** [comment] 2019-10-22 19:48
Closing the issue, assuming this was a false positive and that Trend Micro doesn't report it anymore.

**Closed by ojdkbuild** 2019-10-22 19:48 UTC
