### ISSUE TITLE
Add option for which JDK version to build

### ISSUE THREAD

**Issue by quanah** [ojdkbuild/ojdkbuild#76] opened 2019-04-01 23:35 UTC
The default run.bat only builds JDK8.  It would be nice to be able to specify which JDK version to build, with JDK8 as the default.

**Comment by ojdkbuild** [comment] 2019-04-02 13:05
It was intended to have a `run.bat` as a simple script, that can both checkout deps (submodules) and do a "default" build. All options are handled by CMake, I think it is a bad idea to introduce another layer of options in a bat file. Maybe it is better to remove `run.bat` altogether, and require to run CMake directly (documenting properly how to do it).

Closing this issue in favor of #75

**Closed by ojdkbuild** 2019-04-02 13:05 UTC
