### ISSUE TITLE
Windows Installer not setting JAVA_HOME environment variable when using Installer Parameter ADDLOCAL=ALL

### ISSUE THREAD

**Issue by mandragor59** [ojdkbuild/ojdkbuild#79] opened 2019-04-25 18:23 UTC
after silent install of "java-1.8.0-openjdk-1.8.0.212-1.b04" with parameter ADDLOCAL=ALL JAVA_HOME environment variable is not set. Also path and enviroment for IcedTea-Web etc. not have been set.

**Comment by ojdkbuild** [comment] 2019-04-26 12:27
Hi, thanks for report, but I cannot reproduce this.

After running the following in admin console:

    msiexec /q /i java-1.8.0-openjdk-1.8.0.212-1.b04.ojdkbuild.windows.x86_64.msi ADDLOCAL=ALL

In another console I see the following:

    > java -version
    openjdk version "1.8.0_212-1-ojdkbuild"
    OpenJDK Runtime Environment (build 1.8.0_212-1-ojdkbuild-b04)
    OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

    > echo %JAVA_HOME%
    C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.212-1\

    > javaws
    (window opened)

Can you please check, that this msiexec invocation actually works for that user (that it is not some older jdk version left there)?

If it works, but not install all the components with `ADDLOCAL=ALL`, please try to list the [components](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures#openjdk-8-installation-features) explicitly:

    ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_env_vendor_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env,webstart_migrate,update_notifier

Also please note, that `8u201` CANNOT be updated to `8u212`, older version must be uninstalled first.

**Comment by mandragor59** [comment] 2019-04-26 19:55
Hi, i'm talking about a fresh installation with a gpo from our distribution-server.


ADDLOCAL=ALL does not set the environment, but explicit specifying the components is working.
Same procedure with 8u201 was working. Absolutely shure, our distribution-server does an uninstall of 8u201 before installing 8u212.
A difference may be, that the server pushes over the "system"-Account and not an admin-account.

Mit freundlichen Grüßen / With kind regards

Andreas Lechte





Dear spies, members and minions of the Five Eyes Alliance, ladies and gentlemen! This e-mail has been sent from within the borders of the Federal Republic of Germany. This is a sovereign state. This sovereign state has strict laws for protecting the data and privacy of its citizens. Therefore it is strictly prohibited to record, store or digitally evaluate this e-mail message outside its destination. Please keep this in mind while you minding your business. Thank you very much. [#PRISM #noPRISM #tempora]







Original Message processed by david® 
Re: [ojdkbuild/ojdkbuild] Windows Installer not setting JAVA_HOME environment variable when using Installer Parameter ADDLOCAL=ALL (#79) 26. April 2019, 14:27 Uhr 
Von ojdkbuild 
An ojdkbuild/ojdkbuild 
Cc (2) mandragor59|Author 


Hi, thanks for report, but I cannot reproduce this.
After running the following in admin console:
msiexec /q /i java-1.8.0-openjdk-1.8.0.212-1.b04.ojdkbuild.windows.x86_64.msi ADDLOCAL=ALL
In another console I see the following:
> java -version
openjdk version "1.8.0_212-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_212-1-ojdkbuild-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

> echo %JAVA_HOME%
C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.212-1\

> javaws
(window opened)
Can you please check, that this msiexec invocation actually works for that user (that it is not some older jdk version left there)?
If it works, but not install all the components with ADDLOCAL=ALL, please try to list the components explicitly:
ADDLOCAL=jdk,jdk_registry_standard,jdk_env_path,jdk_env_java_home,jdk_env_vendor_java_home,jdk_registry_jar,openjfx,webstart,webstart_registry,webstart_env,webstart_migrate,update_notifier
Also please note, that 8u201 CANNOT be updated to 8u212, older version must be uninstalled first.

**Comment by ojdkbuild** [comment] 2019-04-30 09:59
> ADDLOCAL=ALL does not set the environment, but explicit specifying the components is working.

M, if `ALL` works differently in some scenarios, I don't think there is anything on MSI side that can help.

Closing the issue, assuming that specifying the explicit list of features works correctly.

**Closed by ojdkbuild** 2019-04-30 09:59 UTC
