### ISSUE TITLE
Time schedule for providing OpenJDK11 binaries?

### ISSUE THREAD

**Issue by GitMensch** [ojdkbuild/ojdkbuild#38] opened 2018-07-30 12:08 UTC
As the Java 11 is the next LTS version after version 8, the GA expected September 2018 and Oracle's "commercial customers" get EOL for version 8 in January 2019 it would be nice to include early access builds for OpenJDK 11 (also ensuring that everything in the build process works until GA of version 11).

Do you consider providing "early" access builds for upcoming version 11? If yes: Do you have a rough time schedule for this?

**Comment by ojdkbuild** [comment] 2018-07-30 12:30
Hi, I am going to add support for jdk11 builds (and to retire jdk10 builds) in September, but the first release (binaries to download) of jdk11 is planned only in October/November after the fist jdk11 update.

Please also note, that OpenJDK 8 binaries in this project are going to be updated after Oracle EOL at least until October 2020 (and possibly some years longer).

I'll leave this issue open and will update it with the info about jdk11 once it is added.

**Comment by GitMensch** [comment] 2018-07-30 12:46
@ojdkbuild Thank you for the news and your efforts.

Will try to use the http://jdk.java.net/11/ binaries until then (at least they include more targets than they did before).

**Comment by ojdkbuild** [comment] 2018-08-28 10:36
Update on jdk11 plans - unlike the jdk10, that was based on upstream sources, jdk11 is going to be based on java-11-openjdk package from CentOS 7 (it is not yet there, likely to be added with 7.6 update). Planned date for first release is late October 2018.

Also an update about the jdk8 lifetime - projected maintenance period for it in this project is extended to June 2023 (to match the lifetime in RHEL/CentOS):

https://access.redhat.com/articles/1299013#OpenJDK_Lifecycle_Dates_and_RHEL_versions

**Comment by gitoss** [comment] 2018-10-05 19:07
Thanks for maintaining the packages - afafik your releases are the only Windows x86 builds left which gives your work special importance.

**Comment by ojdkbuild** [comment] 2018-10-05 20:02
Thanks for kind words! But I am afraid they are not fully deserved regarding win-x86:

1. for jdk8, I believe win-x86 builds are available in other places too (at least both Oracle and Azul download pages list them)

2. jdk11 will not support win-x86 (some [details](https://github.com/ojdkbuild/ojdkbuild/issues/47#issuecomment-427409077))

3. jdk8 win-x86 builds are supported as a "second-tier" arch. While jdk8 win-x86_64 builds are going to be maintained during the whole lifetime of jdk8 in RHEL/CentOS, it may happen that win-x86 builds may be dropped earlier

**Comment by gitoss** [comment] 2018-10-06 14:04
>     2. jdk11 will not support win-x86 (some [details](https://github.com/ojdkbuild/ojdkbuild/issues/47#issuecomment-427409077))

Ugh, that's distressing to hear - some older or cheaper Windows installations still run x86 because the memory is below 4GB and x86 saves memory and storage space.

But because Oracle doesn't support x86 anymore doesn't mean no 3rd party builds? They didn't provide x86 builds for Java10 either. 

I'm hoping for mentioned Linux distros to provide x86 support, which could then be transferred to Windows - or is the Java 10 architecture so different that it's x64 only by design?

**Comment by firehooper** [comment] 2018-10-15 12:54
We also have some legacy 32bit .DLL native files that require x86 (32bit) Java runtime.  We were testing using https://github.com/ojdkbuild/ojdkbuild/releases/download/10.0.2-1/java-10-openjdk-10.0.2-1.b13.ojdkbuild.windows.x86.zip . https://github.com/ojdkbuild/ojdkbuild/commit/8d21482b98f00be64f295ed05cdfeae44c259be9 We were also hoping we might be able to use this project for the Windows x86 jdk11 build.

**Comment by buedi** [comment] 2018-10-15 13:17
We are planning to run Java 11 applications which are backward compatible to Windows 7 (32bit) OS. We were also hoping we might be able to use this project for the Windows x86 jdk11 build.

**Comment by ojdkbuild** [comment] 2018-10-21 21:57
Update on jdk11 progress: 11.0.1 build is being prepared and going to be published in some days (it is not yet released on RHEL).

On windows-x86 builds - I understand the concerns, but can only confirm, that there are no plans to build 32-bit jdk11-win in this project.

If 32-bit jdk8-win is not an option, I can suggest trying jdk11 builds from [SAP](https://github.com/SAP/SapMachine) and [AdoptOpenJDK](https://adoptopenjdk.net/) - according to [this](http://mail.openjdk.java.net/pipermail/jdk-updates-dev/2018-October/000223.html) they are planning to support 32-bit jdk11-win.

**Comment by ojdkbuild** [comment] 2018-10-21 21:58
@gitoss 

> x86 saves memory

That is generally correct for native code, but Java on x86_64 uses compressed pointers, that makes RAM usage not that different from x86. I can suggest [this article](https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/) for tuning JVM for low-RAM. 

> But because Oracle doesn't support x86 anymore doesn't mean no 3rd party builds? 

That mostly means, that there is a good chance that some update will break x86 build and there won't be anybody interested enough to fix it promptly. For other builds - please see the links above.

> I'm hoping for mentioned Linux distros to provide x86 support, which could then be transferred to Windows

Given that Red Hat dropped x86 support alredy 4 years ago (starting with RHEL 7) I'd rather not rely so much on Linux x86 builds.

> is the Java 10 architecture so different that it's x64 only by design

No, the dev process is "evolution-like" and jdk10 runtime is not that different from 9, but parts of the codebase that are not built/tested regularly are going to rot quite fast.

**Comment by firehooper** [comment] 2018-10-25 18:42
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-windows-x86-32-hotspot/

**Comment by GitMensch** [comment] 2018-10-25 18:58
@firehooper Nice, looks promising.
Where do you see the actual build scripts/source repo (revisions)/... in there?

**Comment by buedi** [comment] 2018-10-26 10:37
@ojdkbuild Thanks a lot! Your work is really helpful for a our windows desktop projects. I think this project can be the leading Java build projects in the future if you can continue the support (and allow the optional msi installer integration of) for: webstart (with iced-tea), JavaFX (from the open FX project) and maybe 32 bit compiled version for old clients.

**Comment by ojdkbuild** [comment] 2018-10-26 10:38
@1of16 , 11.0.1 does not include icedtea-web, going to include it into the following versions of jdk11 installer once jd11 support in icedtea-web is stable. Related [maillist thread](http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2018-August/040043.html).

**Comment by 1of16** [comment] 2018-10-26 10:40
@ojdkbuild sounds good. thank you for the fast answer and your great work!

**Comment by ojdkbuild** [comment] 2018-10-26 10:53
@buedi 

> Thanks a lot! Your work is really helpful for a our windows desktop projects.

You are welcome!

> I think this project can be the leading Java build projects in the future

I think this is a bit of overstatement - this project is focused on "linux-compatible" jdk-win builds. In future it is likely going to be an official (supported and endorsed by upstream OpenJDK) set of public jdk LTS binaries. I think this "new place" (unrelated to ojdkbuild) is going to be a "leading Java build project" for LTS releases.

> webstart

Yes, it is planned to be added to jdk11 MSI.

> JavaFX

I am not sure that it can be meaningfully included with jdk11+. With jdk8 it was just a set of files, that can be dropped on top of jdk installation. With jdk10 it was built as an integral part of jdk (set of jdk modules). With jdk11+ it is now [fully standalone](https://openjfx.io/) and it may be better to use it as a third-party JPMS module.

> 32 bit compiled version

Sorry, only 64-bit windows builds are going to be supported for jdk11+ .

**Comment by ojdkbuild** [comment] 2018-10-26 10:55
11.0.1 binaries published ([maillist announce](https://groups.google.com/forum/#!msg/ojdkbuild/1GwscnGlAQc/PWfdzJjCBgAJ)), closing this issue.

**Closed by ojdkbuild** 2018-10-26 10:55 UTC

**Comment by firehooper** [comment] 2018-10-26 21:52
@GitMensch  https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh .  There is also a JRE (for now).
